### ISSUE TITLE
move extensions to subfolder `extensions`

### ISSUE THREAD

**Issue by Luro02** [faldez/tanoshi-extensions#29]
https://matklad.github.io/2021/08/22/large-rust-workspaces.html

```toml
[workspace]
members = ["extensions/*"]
```

(so one does not have to add the extension to the `Cargo.toml` in the root)
